#!/usr/bin/ruby

input_array = [
  "mgdsdwqulhrinkatfjoyzxcbvq",
  "megsdwpulhrinkasfjdyzxcbvk",
  "megsdwpulhmibkatfjoyzccbvq",
  "megsdwtuohrinkatfjoyzecbvq",
  "megsdwpulhdinkatfyoyzxcbvb",
  "megszwpulhrirkatfjoyexcbvq",
  "eegsdwpulhzinkatfjoyzxdbvq",
  "megsdwpulhginkatfjoyqucbvq",
  "leqsdwpulhrinkatfeoyzxcbvq",
  "megsdwpblhrandatfjoyzxcbvq",
  "megrdwpudhrinvatfjoyzxcbvq",
  "mlgsdwpulhrinkatfuoyzxcbyq",
  "mensdwpunhrinsatfjoyzxcbvq",
  "megsdwpnlhrinqatfjoyzxcbuq",
  "megsdwpnlhrinkatfqoysxcbvq",
  "megsdwpulhrinkjtfjoywxobvq",
  "megsdwpclhbinkaffjoyzxcbvq",
  "mersdwpulhrinkattjoyzxcbdq",
  "megsddpwohrinkatfjoyzxcbvq",
  "mejsdwpulhrinratfjoyzxcbvl",
  "megsdwpujhrinkatfjkbzxcbvq",
  "megsdwpujhrinkatfjoyircbvq",
  "megsdwgulhrinkatojoyzxcbvm",
  "qegsdwpulhrinkatfjoyzxggvq",
  "megsdwpflhrinkatfjsazxcbvq",
  "megsdwpulhridkagfjoyzzcbvq",
  "mejsdwpulhriykatfjoyyxcbvq",
  "measdwpulhriakatfjoyzacbvq",
  "mebsdwpulhrinkatfjoyzxmyvq",
  "megsdwpflnrinkatfjoyzxcbxq",
  "megsdwpulhxinuatfjoytxcbvq",
  "megsdwsflhrinkatfjoyzxcmvq",
  "megsdwpuuhritkarfjoyzxcbvq",
  "megsdwpulhrinkazfjoyexcjvq",
  "megsdwpulhrifkatfjokzxcbvc",
  "megsdwmulvrinkatfjoyzxcblq",
  "meggdwpulhrfnkatfjoybxcbvq",
  "megsdwptlhrindatyjoyzxcbvq",
  "megsdwpulhrinkauqjoyzxibvq",
  "megsdwddlhrifkatfjoyzxcbvq",
  "megddwpulhrinkagfjoyzxcbva",
  "messdupulhrinkatfjoyzxqbvq",
  "megsdwpuahrinkatfjotzxchvq",
  "megsewpulhrankathjoyzxcbvq",
  "megsdwpulhrinkatfjoynqcbvv",
  "megsdwpulhrifkatfjotzxcbtq",
  "megsdjpulcrinkitfjoyzxcbvq",
  "fefsowpulhrinkatfjoyzxcbvq",
  "megsdwpulapinkatfjoyzvcbvq",
  "mejsdwpularinkatfjonzxcbvq",
  "megsxwpllrrinkatfjoyzxcbvq",
  "megsdlpulxvinkatfjoyzxcbvq",
  "megsdwpulhriekztfjoyzxxbvq",
  "megspwpulhrinuatfjoyzxcgvq",
  "megqdwpulhrinkatfjoyzujbvq",
  "megsdtpuehrinkatfjoyzxtbvq",
  "megsdwjulhrmnmatfjoyzxcbvq",
  "megjdwpulhrinkztfjoyzpcbvq",
  "megsdwpuljrinkawfjlyzxcbvq",
  "mewsdwpulhtinkatfjodzxcbvq",
  "megsdwpulhrinkatfcoizxcmvq",
  "meisdwpulhrinkatawoyzxcbvq",
  "megshwpulhrinkatfjoyzxcbtz",
  "megsdwpulhfinkatfjowzxcbvj",
  "megodwpulhrcskatfjoyzxcbvq",
  "megydxpulhrinkatfjofzxcbvq",
  "megsdwpulhrinkatljoytxdbvq",
  "mwgsdwpulyrinkatfjoyzxvbvq",
  "meesdwpulhrinkatfjcwzxcbvq",
  "cegsdwpwlhrinkatfioyzxcbvq",
  "megsdwpulhrinkatfqhyxxcbvq",
  "megsrrpulhrxnkatfjoyzxcbvq",
  "megsdgpulhrinkatfjoypxcbnq",
  "xegsdwpulhrinkaxkjoyzxcbvq",
  "mngsdwpulhrenkatfjofzxcbvq",
  "mecsdwpulhrinkabfjoozxcbvq",
  "pegsdkpulhrinkatfuoyzxcbvq",
  "megpdwpughrinkatfjoyzxzbvq",
  "mxgrdwpulhrinyatfjoyzxcbvq",
  "megsdwpulhpigkatfjoyzxcbfq",
  "mhgsdwpulhrinkagfjoxzxcbvq",
  "megsdwpblhtinkatfjqyzxcbvq",
  "megsawvulhrinkatfjoyzxcfvq",
  "metsuwpulhrinkatfjowzxcbvq",
  "mexsdwpulhrinkatsjoyzxvbvq",
  "megtdwpulhrinkatfjoizxcpvq",
  "megidwpjlhrinkatfdoyzxcbvq",
  "megsdwpuljrivkatfjoyqxcbvq",
  "mespdppulhrinkatfjoyzxcbvq",
  "megsdcpulhminkatftoyzxcbvq",
  "megsdwpulhriskatfjayzlcbvq",
  "mejsdwpulhrinkatfvoyzxibvq",
  "megfdwputhriykatfjoyzxcbvq",
  "megsdwparhrinkbtfjoyzxcbvq",
  "mtgsdwpulhmingatfjoyzxcbvq",
  "megsdwjulhrinkatfjtyzxtbvq",
  "megsvwpulhrinkatfjoyzecbvf",
  "megsdwpulprinkatyqoyzxcbvq",
  "zegsdwpulhwinkatfjoyzxcfvq",
  "megsdwiulhrinkatfjoyzxcjcq",
  "aegsdwpulirinkatfjoyvxcbvq",
  "mepsdwculbrinkatfjoyzxcbvq",
  "msgsdcpulhrinkctfjoyzxcbvq",
  "megsdwpulhrinkatfjoozxfevq",
  "megscwpulhrinkatmjoyzxcbsq",
  "megsdwpulhrinkltfjoyzxtmvq",
  "megsddpulhrixkatfjyyzxcbvq",
  "megsdwpulhrinkctfjoqzhcbvq",
  "megsbapblhrinkatfjoyzxcbvq",
  "megsdwpulhrinkatfjoyyxgpvq",
  "mwpsdwpulhrinkutfjoyzxcbvq",
  "megsdwpulhrinvnlfjoyzxcbvq",
  "megsdwsulorinkakfjoyzxcbvq",
  "mbgsdwpulhrinkktfjoyzxcbvg",
  "megddwpulhrindatfjoyzxcbvr",
  "memsdwpulhrinkatqjoyzxcbvo",
  "megsdwpulbrinkarfjoyzxcbxq",
  "megsdwpulhrilkatfjoynxcgvq",
  "mxgsdzpulhrinkatfjoydxcbvq",
  "megsawpulhrinkotfjoyzacbvq",
  "measdwpulhrinkctvjoyzxcbvq",
  "medsdwpulhtinkaqfjoyzxcbvq",
  "megsdwsulhrknkatfjoylxcbvq",
  "megadwpulhrinkatfjkyzxcbvh",
  "mygsdwpulhrinkatfboyzxcavq",
  "megsdwpulhrinkaufjxyzccbvq",
  "mtgsdwpulhrunkatfkoyzxcbvq",
  "megsdwpulhrinkamfwryzxcbvq",
  "meesdwpulhrgnkatnjoyzxcbvq",
  "megddwpolhrinkatfjoyixcbvq",
  "megsdwpulhrinsatfjoyzicwvq",
  "mmgsdwpulhrinkltfjoyzxcgvq",
  "meisdwpulhhinkatfjoyzxubvq",
  "megpdwpulhrinkatfroyzxcbkq",
  "megszwpuhhrinkatfjoyzxcbzq",
  "mersdwpulhrikcatfjoyzxcbvq",
  "mjgsdwpulhrinratfjoyzxcbvl",
  "megsdwnulkxinkatfjoyzxcbvq",
  "megsdwpulhrinkatlaoyzxpbvq",
  "megsdwpulhribkitfjjyzxcbvq",
  "megsdwpzlhrinkalfjoyzkcbvq",
  "megsdwpulhrinkutfjoyzxcdnq",
  "mfgpdwputhrinkatfjoyzxcbvq",
  "oegshwpclhrinkatfjoyzxcbvq",
  "megvdwxulhrinkatfjowzxcbvq",
  "mrgydwpulhrinkatfjoyzxcbvl",
  "megsdwpuqhrinkaxfjoyzxcbfq",
  "megsdwpughrinixtfjoyzxcbvq",
  "megsdwpslxrinkatfjoyzxcbvl",
  "megsdwpukhrinkatfjovzxnbvq",
  "megsdwpulnrinkrtojoyzxcbvq",
  "megsdwpuvhrinkatfjjyzxclvq",
  "vegrdwpulhrinzatfjoyzxcbvq",
  "melsdwwulvrinkatfjoyzxcbvq",
  "megsdwpulhrizkbtfjoyzjcbvq",
  "megsdwpulhrinlatfjoyzkcbvr",
  "megsdweulhrinkaofqoyzxcbvq",
  "megsdcpulhrifkatfdoyzxcbvq",
  "negsdwpulhainkztfjoyzxcbvq",
  "megsdwpklhrinkttfjoyzxvbvq",
  "megsdwpothrdnkatfjoyzxcbvq",
  "megsdwpulvrinkatfaoyzxcbvr",
  "mewsdwpulhrinkatfooyzxtbvq",
  "megtdwpulhrinkatfxoyzxcbvy",
  "zegsdwpulhrinkamljoyzxcbvq",
  "mkgodwpulhrcnkatfjoyzxcbvq",
  "megsdepularinkatfjoyzxybvq",
  "segsdwpulhrinkatfmoyzycbvq",
  "mbgsdwpulhrsnkztfjoyzxcbvq",
  "megsdwpmlhrinkatfjxyzhcbvq",
  "megsdwpulhrinkatfboyqxmbvq",
  "megsdwpulhrinkadtpoyzxcbvq",
  "megsdmpulhrjnkatfjoyzxwbvq",
  "megsdwpulhrivkatfroywxcbvq",
  "megsdwdulhrinkatpjwyzxcbvq",
  "megsdwpylhrdrkatfjoyzxcbvq",
  "megsdwpulhrvnkptfjoyzlcbvq",
  "megsdwpuihridkatfjuyzxcbvq",
  "megsdwpulhbiikatfjxyzxcbvq",
  "meggdwpulurinkatfjoyaxcbvq",
  "mehsnwpulcrinkatfjoyzxcbvq",
  "megsdwpulhrinkatfjoczdclvq",
  "megsdwjulhrinkatfhkyzxcbvq",
  "megsdwpulhrinoatfjoyzxcwvy",
  "megpdwpelhrfnkatfjoyzxcbvq",
  "megsjwpulhrwnkatfjdyzxcbvq",
  "megsdwpulhrbniatfjoyzxcbpq",
  "megsdwpulhrwnkatfjoydxcpvq",
  "megsdwrulhrinkatfjvyixcbvq",
  "yegvdwpulhtinkatfjoyzxcbvq",
  "meosdwpulhrinkatfjhyzxsbvq",
  "mjgsdwpulhrinkatfjoyyxcjvq",
  "megsdwpulhrinkatfnoyzlmbvq",
  "mehsdfkulhrinkatfjoyzxcbvq",
  "megsdwpuahrinkatfyoyzxcwvq",
  "megsdwpulhyinkatfjobzkcbvq",
  "megsdwpjlhrinkatfnoyzscbvq",
  "megsdwiulhrinqatfjoyzxcavq",
  "megsdwpulurinkatfjoykxcbmq",
  "megsdwpmlhvinkatfjotzxcbvq",
  "megswwpulhrinfatfjoytxcbvq",
  "mxgsdwpulhrrnkatfjoyhxcbvq",
  "megubwpulhrinkaafjoyzxcbvq",
  "megsdwpulhrdnsztfjoyzxcbvq",
  "megsdwpulhronkgtfjhyzxcbvq",
  "megsdwzulhfinratfjoyzxcbvq",
  "megsdwpulhrinkrtfjqyixcbvq",
  "megspwpulhrinkatfjoywxcavq",
  "megmfjpulhrinkatfjoyzxcbvq",
  "lelsdwpulhrinsatfjoyzxcbvq",
  "megsdwnultrinkatfjoyzxybvq",
  "megsdwpulhdnnkatfjpyzxcbvq",
  "megsdwpulhzinkatfjoyzhcpvq",
  "megoddpulhrilkatfjoyzxcbvq",
  "megsdvpulhrwnkatfjoyzxcbdq",
  "megsdwpulhmikkatfjoyzxcbvr",
  "meesdwpulhrinkaofjoazxcbvq",
  "megndwhulhrinfatfjoyzxcbvq",
  "megsdwpulhjihkatfjoyzxcbvb",
  "jegsdwpulhrinkattjoszxcbvq",
  "megsdwpulhrenkatfjodzxcbvp",
  "mefsdwpulhrinkatfjoyzxcczq",
  "megsdwpulhrknkatfjovzxcbvb",
  "megytwpulhrinkatfjoyzxcbvo",
  "csgsdwpulhrinkatdjoyzxcbvq",
  "megsbwpulhrinkazfjtyzxcbvq",
  "mrgsdwpulhjinkatfjoyzxcbvm",
  "megsywzulhrinkatfjofzxcbvq",
  "megxdwpulhrndkatfjoyzxcbvq",
  "mcgsdwpuphrixkatfjoyzxcbvq",
  "megsdlpulxvinkatfvoyzxcbvq",
  "megsdwpulhrinfatfjoyzicbvo",
  "megwgwpulhrinpatfjoyzxcbvq",
  "mggsdwpulhrinkatfjtrzxcbvq",
  "msgsdwpulirinkatfjoyzxcbaq",
  "megsdwpulhrineatfeoyzxcbvl",
  "megsdnpulhrinkatojoyzxcbvb",
  "mfgsdwpulhdinkatmjoyzxcbvq",
  "megsdwpulhrinkawfjuyzxcbvg",
  "megsdwpulhrincatfjoyzxcxvu",
  "mevsdwzplhrinkatfjoyzxcbvq",
  "megskweulhfinkatfjoyzxcbvq",
  "mebsdvpulhrinkatfjoyzxcbkq",
  "megddwiulhrinkatfioyzxcbvq",
  "mygsdwpulhqinkatfooyzxcbvq",
  "megsdweulhrfnkatfjoybxcbvq",
  "mrgsdhpulmrinkatfjoyzxcbvq",
  "megsdwkukhrinkatftoyzxcbvq",
  "megsqwpulhrinfatfjoyzxebvq",
  "megsdwpulhriskanfjoyzxctvq"
]

num_doubles = 0
num_triples = 0

input_array.each do |id|
  contains_double = false
  contains_triple = false

  char_array = id.chars
  hash_map = {}

  char_array.each do |char|
    if hash_map[char] == nil
      hash_map[char] = 1
    else
      hash_map[char] = hash_map[char] + 1
    end
  end

  hash_map.values.each do |value|
    if value == 2
      contains_double = true
    elsif value == 3
      contains_triple = true
    end
  end

  if contains_double
    num_doubles += 1
  end
  if contains_triple
    num_triples += 1
  end
end

puts num_doubles * num_triples
